name: Build

on: [push]

jobs:
  Build:
    name: Build iscc-eval / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Set up Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.4.0

    - name: Disable Poetry Modern Installer
      if: matrix.os == 'windows-2019'
      run: poetry config installer.modern-installation false

    - name: Install iscc-eval dependencies
      run: poetry install

    - name: Install UPX MacOS
      if: matrix.os == 'MacOS'
      run: brew install upx

    - name: Install UPX Windows
      if: matrix.os == 'Windows'
      run: choco install upx

    - name: Install UPX Ubuntu
      if: matrix.os == 'Ubuntu'
      run: sudo apt-get install -y upx

    - name: Build iscc-eval
      run: poetry run python build.py

    - uses: actions/upload-artifact@v3
      with:
        name: iscc-eval-${{ matrix.os }}
        path: dist/*
